### ISSUE TITLE
Error when running indices.AppendNDVI in TorchGeo v0.4

### ISSUE THREAD

**Issue by osgeokr** [microsoft/torchgeo#1079]
### Description

This error was confirmed in a recently updated TorchGeo v0.4 environment.
You can reproduce this error message by running the Indices Tutorial, provided on [TorchGeo's official website](https://torchgeo.readthedocs.io/en/stable/tutorials/indices.html).

```
index = indices.AppendNDVI(index_nir=3, index_red=0)
```

```
output:
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
[<ipython-input-8-b3a2e560c004>](https://localhost:8080/#) in <module>
      1 # NDVI is appended to channel dimension (dim=0)
      2 index = indices.AppendNDVI(index_nir=3, index_red=0)
----> 3 sample1 = index(sample1)
      4 sample2 = index(sample2)
      5 

1 frames
[/usr/local/lib/python3.8/dist-packages/kornia/augmentation/base.py](https://localhost:8080/#) in forward(self, input, params, **kwargs)
    173         """
    174         in_tensor = self.__unpack_input__(input)
--> 175         input_shape = in_tensor.shape
    176         in_tensor = self.transform_tensor(in_tensor)
    177         batch_shape = in_tensor.shape

AttributeError: 'dict' object has no attribute 'shape'
```

### Steps to reproduce

Run the [Indices Tutorial on TorchGeo's official website (Colab)](https://colab.research.google.com/github/microsoft/torchgeo/blob/releases/v0.4/docs/tutorials/indices.ipynb)

It has been confirmed that the same code works fine in the TorchGeo v0.3 environment.
Perhaps some code changes in indices.py caused this error.

### Version

0.4.0

**Comment by adamjstewart** [comment]
It appears that you're using the v0.3 version of the tutorial with the v0.4 version of TorchGeo. v0.4 includes a backwards incompatible change (#999), and all transforms now take Tensors as input instead of dicts. You'll need to use matching versions of TorchGeo and its tutorials to get things to work.

**Comment by osgeokr** [comment]
I was misundertood by not noticing the incompatible change. Thank you for answer. :)
